/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminas_vF;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Oswald
 */
public class Ventana extends javax.swing.JFrame {

    private static Juego buscaminas = new Juego(); //instancia de clase Juego en JFrame
    ImageIcon imagen1 = new ImageIcon(this.getClass().getResource("img/fotoMina.png")); //ImageIcon para imagenes

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        deshabilitarBotones(); //botones empiezan setEnabled(false)
    }//constructor ventana JFrame

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbCantidad = new javax.swing.JComboBox<>();
        btnPartidasGanadas = new javax.swing.JButton();
        btnPartidasPerdidas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 4, 4));

        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);

        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10);

        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11);

        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12);

        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel1.add(b13);

        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel1.add(b14);

        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        jPanel1.add(b15);

        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        jPanel1.add(b16);

        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        jPanel1.add(b17);

        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        jPanel1.add(b18);

        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        jPanel1.add(b19);

        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        jPanel1.add(b20);

        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel1.add(b21);

        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel1.add(b22);

        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        jPanel1.add(b23);

        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        jPanel1.add(b24);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 840, 400));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        btnSeleccionar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad de Minas (mínimo 3, máximo 10)");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbCantidad.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cmbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnPartidasGanadas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPartidasGanadas.setText("Partidas Ganadas");
        btnPartidasGanadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidasGanadasActionPerformed(evt);
            }
        });

        btnPartidasPerdidas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPartidasPerdidas.setText("Partidas Perdidas");
        btnPartidasPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidasPerdidasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad de partidas ganadas y perdidas");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUSCAMINAS");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPartidasGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPartidasPerdidas))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionar)
                            .addComponent(btnPartidasGanadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPartidasPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        buscaminas.inicializar();
        if (buscaminas.seleccionarMinas(Integer.parseInt(cmbCantidad.getSelectedItem().toString()))) {
          
            habilitarBotones();
        } else {
            deshabilitarBotones();
        }

        b0.setIcon(null);
        b1.setIcon(null);
        b2.setIcon(null);
        b3.setIcon(null);
        b4.setIcon(null);
        b5.setIcon(null);
        b6.setIcon(null);
        b7.setIcon(null);
        b8.setIcon(null);
        b9.setIcon(null);
        b10.setIcon(null);
        b11.setIcon(null);
        b12.setIcon(null);
        b13.setIcon(null);
        b14.setIcon(null);
        b15.setIcon(null);
        b16.setIcon(null);
        b17.setIcon(null);
        b18.setIcon(null);
        b19.setIcon(null);
        b20.setIcon(null);
        b21.setIcon(null);
        b22.setIcon(null);
        b23.setIcon(null);
        b24.setIcon(null);

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(0)) {
            b0.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b0.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }

        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b0.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b0.setIcon(null);
        }

    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(1)) {
            b1.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b1.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }

        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b1.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b1.setIcon(null);
        }

    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(2)) {
            b2.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b2.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b2.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b2.setIcon(null);
        }

    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(3)) {
            b3.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b3.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b3.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b3.setIcon(null);
        }

    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(4)) {
            b4.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b4.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b4.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b4.setIcon(null);
        }

    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(5)) {
            b5.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b5.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b5.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b5.setIcon(null);
        }

    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(6)) {
            b6.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b6.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b6.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b6.setIcon(null);
        }

    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(7)) {
            b7.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b7.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b7.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b7.setIcon(null);
        }

    }//GEN-LAST:event_b7ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(17)) {
            b17.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b17.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b17.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b17.setIcon(null);
        }

    }//GEN-LAST:event_b17ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(8)) {
            b8.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b8.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b8.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b8.setIcon(null);
        }

    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(9)) {
            b9.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b9.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b9.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b9.setIcon(null);
        }

    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(10)) {
            b10.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b10.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b10.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b10.setIcon(null);
        }

    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(11)) {
            b11.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b11.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b11.setIcon(null);
            
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b11.setIcon(null);
        }

    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(12)) {
            b12.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b12.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b12.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b12.setIcon(null);
        }

    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(13)) {
            b13.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b13.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b13.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b13.setIcon(null);
        }

    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(14)) {
            b14.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b14.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b14.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b14.setIcon(null);
        }

    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(15)) {
            b15.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b15.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b15.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b15.setIcon(null);
        }

    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(16)) {
            b16.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b16.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b16.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b16.setIcon(null);
        }

    }//GEN-LAST:event_b16ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(18)) {
            b18.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b18.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b18.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b18.setIcon(null);
        }

    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(19)) {
            b19.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b19.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b19.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b19.setIcon(null);
        }

    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(20)) {
            b20.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b20.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b20.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b20.setIcon(null);
        }

    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(21)) {
            b21.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b21.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b21.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b21.setIcon(null);
        }

    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(22)) {
            b22.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b22.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b22.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b22.setIcon(null);
        }

    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(23)) {
            b23.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
        } else {
            b23.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b23.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b23.setIcon(null);
        }

    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        if (buscaminas.buscarMina(24)) {
            b24.setIcon(imagen1);
            Juego.cantidadVidas++;
            Juego.contadorMinas++;
            mostrarVidas();
            
        } else {
            b24.setEnabled(false);
            Juego.cantidadVidas--;
            mostrarVidas();
            
        }
        if (Juego.cantidadVidas == 0) {
            JOptionPane.showMessageDialog(null, "Perdiste.");
            Juego.partidasPerdidas++;
            deshabilitarBotones();
            b24.setIcon(null);
        }

        if (Juego.contadorMinas == Integer.parseInt(cmbCantidad.getSelectedItem().toString()) && Juego.cantidadVidas >= 1) {
            JOptionPane.showMessageDialog(null, "Ganaste.");
            Juego.partidasGanadas++;
            deshabilitarBotones();
            b24.setIcon(null);
        }

    }//GEN-LAST:event_b24ActionPerformed

    private void btnPartidasGanadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidasGanadasActionPerformed
          // TODO add your handling code here:
          JOptionPane.showMessageDialog(null, "Partidas ganadas: " + Juego.partidasGanadas);
    }//GEN-LAST:event_btnPartidasGanadasActionPerformed

    private void btnPartidasPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidasPerdidasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Partidas perdidas: " + Juego.partidasPerdidas);
    }//GEN-LAST:event_btnPartidasPerdidasActionPerformed

    // mostrar cantidad vidas
    private void mostrarVidas() {
        JOptionPane.showMessageDialog(null, "Cantidad de vidas: " + Juego.cantidadVidas);
    }
    //habilitar-deshabilitar botones
    public void habilitarBotones() {
        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        b10.setEnabled(true);
        b11.setEnabled(true);
        b12.setEnabled(true);
        b13.setEnabled(true);
        b14.setEnabled(true);
        b15.setEnabled(true);
        b16.setEnabled(true);
        b17.setEnabled(true);
        b18.setEnabled(true);
        b19.setEnabled(true);
        b20.setEnabled(true);
        b21.setEnabled(true);
        b22.setEnabled(true);
        b23.setEnabled(true);
        b24.setEnabled(true);

        b0.setIcon(null);
        b1.setIcon(null);
        b2.setIcon(null);
        b3.setIcon(null);
        b4.setIcon(null);
        b5.setIcon(null);
        b6.setIcon(null);
        b7.setIcon(null);
        b8.setIcon(null);
        b9.setIcon(null);
        b10.setIcon(null);
        b11.setIcon(null);
        b12.setIcon(null);
        b13.setIcon(null);
        b14.setIcon(null);
        b15.setIcon(null);
        b16.setIcon(null);
        b17.setIcon(null);
        b18.setIcon(null);
        b19.setIcon(null);
        b20.setIcon(null);
        b21.setIcon(null);
        b22.setIcon(null);
        b23.setIcon(null);
        b24.setIcon(null);

    }//habilitarBotones

    public void deshabilitarBotones() {
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        b10.setEnabled(false);
        b11.setEnabled(false);
        b12.setEnabled(false);
        b13.setEnabled(false);
        b14.setEnabled(false);
        b15.setEnabled(false);
        b16.setEnabled(false);
        b17.setEnabled(false);
        b18.setEnabled(false);
        b19.setEnabled(false);
        b20.setEnabled(false);
        b21.setEnabled(false);
        b22.setEnabled(false);
        b23.setEnabled(false);
        b24.setEnabled(false);
    }//deshabilitarBotones

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton btnPartidasGanadas;
    private javax.swing.JButton btnPartidasPerdidas;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
